# Generated by Django 3.1.8 on 2022-08-31 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220829_1524'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='statenumbers',
            constraint=models.UniqueConstraint(fields=('game_obj', 'number'), name='not unique game and number'),
        ),
    ]
