# Generated by Django 4.0.1 on 2023-02-17 04:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_game_id_alter_purchasedtickets_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_win_number_card',
            field=models.PositiveIntegerField(blank=True, default=30,
                                              validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='last_win_number_ticket',
            field=models.PositiveIntegerField(blank=True, default=55,
                                              validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
