# Generated by Django 4.0.1 on 2023-02-17 05:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_game_last_win_number_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='last_win_number_card',
            field=models.PositiveIntegerField(blank=True, null=True,
                                              validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='last_win_number_ticket',
            field=models.PositiveIntegerField(blank=True, null=True,
                                              validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
