# Generated by Django 4.0.1 on 2023-02-27 15:36

from django.db import migrations


def get_no_numbers(game_obj):
    list_numbers = [int(num) for num in game_obj.numbers.split(' ')]
    no_numbers = [str(num) for num in
                  sorted([num for num in range(1, 91) if num not in list_numbers])]
    if no_numbers:
        return ' '.join(no_numbers)
    return None


def set_game_no_numbers(app, schema_editor):
    Game = app.get_model('app', 'Game')

    for game_obj in Game.objects.all():
        game_obj.no_numbers = get_no_numbers(game_obj)
        game_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_game_no_numbers'),
    ]

    operations = [
        migrations.RunPython(set_game_no_numbers),
    ]
