# Generated by Django 4.0.1 on 2023-04-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_ticket_number_lottotickets_ticket_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game',
            new_name='game_id',
        ),
        migrations.AddField(
            model_name='game',
            name='add_numbers',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='name_game',
            field=models.CharField(default='name_lotto', max_length=25),
            preserve_default=False,
        ),
    ]
