# Generated by Django 4.0.1 on 2023-04-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_game_game_game_id_game_add_numbers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='no_numbers',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
