# Generated by Django 4.0.1 on 2023-04-14 10:02

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_game_no_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='no_numbers_a',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(89)]), blank=True, null=True, size=89),
        ),
        migrations.AddField(
            model_name='game',
            name='numbers_a',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)]), blank=True, null=True, size=90),
        ),
    ]
