# Generated by Django 4.0.1 on 2023-04-13 08:29

from django.db import migrations


def get_numbers_a(game_obj):
    return [int(num) for num in game_obj.numbers.split(' ')]


def get_no_numbers_a(game_obj):
    list_numbers = [int(num) for num in game_obj.numbers.split(' ')]
    no_numbers_a = [num for num in
                    sorted([num for num in range(1, 91) if num not in list_numbers])]
    return no_numbers_a


def set_game_all_numbers(app, schema_editor):
    Game = app.get_model('app', 'Game')

    for game_obj in Game.objects.all():
        game_obj.numbers_a = get_numbers_a(game_obj)
        game_obj.no_numbers_a = get_no_numbers_a(game_obj)
        game_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_game_no_numbers_a_game_numbers_a'),
    ]

    operations = [
        migrations.RunPython(set_game_all_numbers),
    ]
