# Generated by Django 4.0.1 on 2023-04-14 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20230414_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='no_numbers',
        ),
        migrations.RemoveField(
            model_name='game',
            name='numbers',
        ),
    ]
