# Generated by Django 4.0.1 on 2023-04-14 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_game_no_numbers_remove_game_numbers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='no_numbers_a',
            new_name='no_numbers',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='numbers_a',
            new_name='numbers',
        ),
    ]
