# Generated by Django 4.0.1 on 2023-05-12 03:38

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_game_add_numbers_alter_game_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lottotickets',
            name='game_obj',
        ),
        migrations.AddField(
            model_name='lottotickets',
            name='game_id',
            field=models.CharField(default=1000, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lottotickets',
            name='name_game',
            field=models.CharField(default='study', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lottotickets',
            name='first_seven_numbers',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(
                    validators=[django.core.validators.MinValueValidator(1),
                                django.core.validators.MaxValueValidator(90)]), size=7),
        ),
        migrations.AlterField(
            model_name='lottotickets',
            name='ticket_numbers',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(
                    validators=[django.core.validators.MinValueValidator(1),
                                django.core.validators.MaxValueValidator(90)]), size=30),
        ),
    ]
