# Generated by Django 4.0.1 on 2023-05-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_lottotickets_game_obj_lottotickets_game_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='statenumbers',
            name='not unique game and number',
        ),
        migrations.RemoveField(
            model_name='statenumbers',
            name='game_obj',
        ),
        migrations.AddField(
            model_name='statenumbers',
            name='game_id',
            field=models.CharField(default=1000, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statenumbers',
            name='name_game',
            field=models.CharField(default='study', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='statenumbers',
            constraint=models.UniqueConstraint(fields=('name_game', 'game_id'), name='not unique name_game and game_id'),
        ),
    ]
