# Generated by Django 4.0.1 on 2023-09-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_statenumbers_not unique name_game and game_id_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='game',
            constraint=models.UniqueConstraint(fields=('name_game', 'game_id'), name='not unique name_game and game_id'),
        ),
    ]
